let token=parent.localStorage.getItem('mostakshef_token'),me,grades=[],units=[],lessons=[],quizzes=[],bank=[],students=[],homeBlocks=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function H(){return {'Content-Type':'application/json',Authorization:'Bearer '+token}}
async function api(u,o={}){const r=await fetch(u,{...o,headers:{...H(),...(o.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'حدث خطأ');return d}
function toast(x,type='ok'){const box=$('#aToast');box.className='toast '+type;box.textContent=x;box.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>box.classList.add('hidden'),3000)}
function closeModal(){const m=$('#modal');m.classList.add('hidden');$('#modalBody').innerHTML=''}function openModal(x){$('#modalBody').innerHTML=x;$('#modal').classList.remove('hidden')}
function tab(t){$$('[data-page]').forEach(x=>x.classList.toggle('hidden',x.dataset.page!==t));$$('.adminSide button').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));if(t==='bank')renderBank();if(t==='settings')loadSettings();if(t==='analytics')loadAnalytics();if(t==='parents')loadParents();if(t==='media')loadMedia()}
$$('.adminSide button').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));function esc(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function gradeName(id){return grades.find(x=>x.id===id)?.name||'—'}function unitName(id){return units.find(x=>x.id===id)?.name||'بدون وحدة'}
function gradeSelect(id='gradeId',required=true){return `<select id="${id}" ${required?'required':''}><option value="">اختر الصف</option>${grades.map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join('')}</select>`}
function setFilterOptions(){for(const id of ['unitGradeFilter','lessonGradeFilter','quizGradeFilter']){const el=$('#'+id);if(!el)continue;const old=el.value;el.innerHTML='<option value="">كل الصفوف</option>'+grades.map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join('');el.value=old}}
async function load(){[grades,units,lessons,quizzes]=await Promise.all([api('/api/grades'),api('/api/units'),api('/api/lessons'),api('/api/quizzes')]);setFilterOptions();render();const s=await api('/api/admin/stats');$('#stats').innerHTML=Object.entries({طلاب:s.students,مدرسون:s.teachers,صفوف:s.grades,وحدات:s.units,دروس:s.lessons,اختبارات:s.quizzes,محاولات:s.attempts}).map(([k,v])=>`<div class="stat"><span>${k}</span><b>${v}</b></div>`).join('')}
function empty(t,s){return `<div class="empty"><div class="emptyIcon">📭</div><h3>${t}</h3><p>${s||''}</p></div>`}function render(){renderGrades();renderUnits();renderLessons();renderQuizzes();if(me.role==='admin')renderUsers()}
function renderGrades(){const a=grades;$('#gradesList').innerHTML=a.length?a.map(g=>`<article class="card entityCard"><div class="entityTop"><span class="bigIcon">🎓</span><span class="tag">${g.stage==='primary'?'ابتدائي':'إعدادي'}</span></div><h3>${esc(g.name)}</h3><div class="actions">${me.role==='admin'?`<button onclick="editGrade('${g.id}')">تعديل</button><button class="danger" onclick="deleteGrade('${g.id}')">حذف</button>`:''}</div></article>`).join(''):empty('لا توجد صفوف')}
function renderUnits(){const a=units.filter(u=>(!$('#unitSearch')?.value||u.name.toLowerCase().includes($('#unitSearch').value.toLowerCase()))&&(!$('#unitGradeFilter')?.value||u.gradeId===$('#unitGradeFilter').value));$('#unitsList').innerHTML=a.length?a.map(u=>`<article class="card entityCard"><span class="tag">${esc(gradeName(u.gradeId))}</span><h3>${esc(u.name)}</h3><p>${esc(u.description||'')}</p><div class="actions"><button onclick="editUnit('${u.id}')">تعديل</button><button class="danger" onclick="delEntity('/api/admin/units/${u.id}','الوحدة')">حذف</button></div></article>`).join(''):empty('لا توجد وحدات')}
function renderLessons(){const a=lessons.filter(l=>(!$('#lessonSearchAdmin')?.value||l.title.toLowerCase().includes($('#lessonSearchAdmin').value.toLowerCase()))&&(!$('#lessonGradeFilter')?.value||l.gradeId===$('#lessonGradeFilter').value));$('#lessonsList').innerHTML=a.length?a.map(l=>`<article class="card entityCard"><span class="tag">${esc(gradeName(l.gradeId))}</span><h3>${esc(l.title)}</h3><p>${esc(l.summary||'')}</p><div class="metaLine">${l.youtubeId?'🎬 يوتيوب ':''}${l.videoUrl?'🎞️ فيديو مرفوع ':''}${l.resources?.length||0} ملف</div><div class="actions"><button onclick="editLesson('${l.id}')">تعديل</button><button class="danger" onclick="delEntity('/api/admin/lessons/${l.id}','الدرس')">حذف</button></div></article>`).join(''):empty('لا توجد دروس')}
function renderQuizzes(){const a=quizzes.filter(q=>(!$('#quizSearchAdmin')?.value||q.title.toLowerCase().includes($('#quizSearchAdmin').value.toLowerCase()))&&(!$('#quizGradeFilter')?.value||q.gradeId===$('#quizGradeFilter').value));$('#quizzesList').innerHTML=a.length?a.map(x=>`<article class="card entityCard"><span class="tag">${esc(gradeName(x.gradeId))}</span><h3>${esc(x.title)}</h3><p>${x.questions.length} سؤال · نجاح ${x.passingScore||50}%</p><div class="actions"><button onclick="editQuiz('${x.id}')">تعديل</button><button class="danger" onclick="delEntity('/api/admin/quizzes/${x.id}','الاختبار')">حذف</button></div></article>`).join(''):empty('لا توجد اختبارات')}
async function renderBank(){try{bank=await api('/api/question-bank');$('#bankList').innerHTML=bank.map(x=>`<article class="card"><span class="tag">${esc(gradeName(x.gradeId))}</span><h3>${esc(x.text)}</h3><p>${esc(x.quizTitle)}</p></article>`).join('')||empty('لا توجد أسئلة')}catch(e){toast(e.message,'error')}}
async function renderUsers(){const u=await api('/api/admin/users');$('#usersList').innerHTML=u.map(x=>`<article class="card"><h3>${esc(x.name)}</h3><p>${esc(x.email)}</p><span class="tag">${x.role==='admin'?'مدير':x.role==='teacher'?'مدرس':'طالب'}</span></article>`).join('')}
function openGrade(){openModal(`<form onsubmit="saveGrade(event)"><h2>إضافة صف</h2><label>اسم الصف<input id="n" required></label><label>المرحلة<select id="s"><option value="primary">ابتدائي</option><option value="preparatory">إعدادي</option></select></label><button>حفظ</button></form>`)}function editGrade(id){const g=grades.find(x=>x.id===id);openModal(`<form onsubmit="saveGrade(event,'${id}')"><h2>تعديل صف</h2><label>الاسم<input id="n" value="${esc(g.name)}" required></label><label>المرحلة<select id="s"><option value="primary" ${g.stage==='primary'?'selected':''}>ابتدائي</option><option value="preparatory" ${g.stage==='preparatory'?'selected':''}>إعدادي</option></select></label><button>حفظ</button></form>`)}async function saveGrade(e,id){e.preventDefault();await api(id?'/api/admin/grades/'+id:'/api/admin/grades',{method:id?'PUT':'POST',body:JSON.stringify({name:$('#n').value,stage:$('#s').value})});closeModal();load();tab('grades')}
function openUnit(){openModal(`<form onsubmit="saveUnit(event)">${gradeSelect()}<label>اسم الوحدة<input id="n" required></label><label>الوصف<textarea id="d"></textarea></label><button>حفظ</button></form>`);$('#gradeId').onchange=()=>{}}
function editUnit(id){const u=units.find(x=>x.id===id);openUnit();setTimeout(()=>{$('#gradeId').value=u.gradeId;$('#n').value=u.name;$('#d').value=u.description||'';$('#modalBody form').onsubmit=e=>saveUnit(e,id)},20)}async function saveUnit(e,id){e.preventDefault();await api(id?'/api/admin/units/'+id:'/api/admin/units',{method:id?'PUT':'POST',body:JSON.stringify({gradeId:$('#gradeId').value,name:$('#n').value,description:$('#d').value})});closeModal();load();tab('units')}
function fillUnits(g){$('#unitId').innerHTML='<option value="">بدون وحدة</option>'+units.filter(u=>u.gradeId===g).map(u=>`<option value="${esc(u.id)}">${esc(u.name)}</option>`).join('')}function fillLessons(g){$('#lessonId').innerHTML='<option value="">بدون درس</option>'+lessons.filter(l=>l.gradeId===g).map(l=>`<option value="${esc(l.id)}">${esc(l.title)}</option>`).join('')}
function openLesson(){openModal(`<form id="lessonForm" onsubmit="saveLesson(event)">${gradeSelect()}<select id="unitId"><option value="">بدون وحدة</option></select><label>عنوان الدرس<input id="t" required></label><label>الملخص<input id="s"></label><label>صورة غلاف للدرس<input id="coverImage" placeholder="رابط صورة أو ارفعها من مدير الملفات"><button type="button" onclick="uploadInto('coverImage','image')">رفع صورة</button></label><div class="uploadLine"><label>🎞️ فيديو من الجهاز<input id="videoFile" type="file" accept="video/*"></label><button type="button" onclick="uploadFile('videoFile','videoUrl')">رفع الفيديو</button><input id="videoUrl" placeholder="رابط الفيديو المرفوع" readonly></div><div class="ytPicker"><label>🎬 رابط YouTube</label><input id="yt" placeholder="https://youtu.be/... أو Video ID"><input id="ytt" placeholder="عنوان الفيديو"><button type="button" onclick="openYouTubePicker()">اختيار من القناة (API اختياري)</button><div id="ytPreview"></div></div><label>محتوى الدرس<textarea id="c" rows="8"></textarea></label><div class="uploadLine"><label>📄 PDF أو صورة إضافية<input id="resourceFile" type="file" accept="application/pdf,image/*"></label><button type="button" onclick="uploadResource()">رفع وإضافة الملف</button></div><div id="resourcesBox" class="resourcesAdmin"></div><button id="saveBtn">حفظ الدرس ✓</button></form>`);$('#gradeId').onchange=()=>fillUnits($('#gradeId').value);fillUnits(grades[0]?.id||'')}
let currentResources=[];function renderResourceAdmin(){const b=$('#resourcesBox');if(!b)return;b.innerHTML=currentResources.map((r,i)=>`<div class="resourceRow">${r.type==='pdf'?'📄':'🖼️'} ${esc(r.name)} <button type="button" onclick="currentResources.splice(${i},1);renderResourceAdmin()">حذف</button></div>`).join('')}
async function uploadResource(){const f=$('#resourceFile').files?.[0];if(!f)return toast('اختر ملفًا','error');const r=await uploadRaw(f);currentResources.push(r);renderResourceAdmin();$('#resourceFile').value=''}
async function uploadRaw(file){const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/upload',{method:'POST',headers:{Authorization:'Bearer '+token},body:fd}),d=await r.json();if(!r.ok)throw Error(d.message||'فشل الرفع');return d}
async function uploadFile(input,target){try{const f=$('#'+input).files?.[0];if(!f)return toast('اختر فيديو','error');const r=await uploadRaw(f);$('#'+target).value=r.url;toast('تم رفع الفيديو ✓')}catch(e){toast(e.message,'error')}}async function uploadInto(target,type){try{const f=await pickFile(type);if(f){const r=await uploadRaw(f);$('#'+target).value=r.url;toast('تم رفع الصورة ✓')}}catch(e){toast(e.message,'error')}}function pickFile(type){return new Promise(resolve=>{const i=document.createElement('input');i.type='file';i.accept=type==='image'?'image/*':'*/*';i.onchange=()=>resolve(i.files?.[0]);i.click()})}
function editLesson(id){const l=lessons.find(x=>x.id===id);openLesson();setTimeout(()=>{$('#gradeId').value=l.gradeId;fillUnits(l.gradeId);$('#unitId').value=l.unitId||'';$('#t').value=l.title;$('#s').value=l.summary||'';$('#coverImage').value=l.coverImage||'';$('#videoUrl').value=l.videoUrl||'';$('#yt').value=l.youtubeId||'';$('#ytt').value=l.youtubeTitle||'';currentResources=l.resources||[];renderResourceAdmin();$('#lessonForm').onsubmit=e=>saveLesson(e,id)},30)}
async function saveLesson(e,id){e.preventDefault();try{await api(id?'/api/admin/lessons/'+id:'/api/admin/lessons',{method:id?'PUT':'POST',body:JSON.stringify({gradeId:$('#gradeId').value,unitId:$('#unitId').value||null,title:$('#t').value,summary:$('#s').value,content:$('#c').value,youtubeId:$('#yt').value,youtubeTitle:$('#ytt').value,videoUrl:$('#videoUrl').value,coverImage:$('#coverImage').value,resources:currentResources})});currentResources=[];closeModal();await load();tab('lessons');toast('تم حفظ الدرس ✓')}catch(x){toast(x.message,'error')}}
async function openYouTubePicker(){try{const d=await api('/api/youtube/videos?max=30');if(!d.videos?.length)return toast('لا توجد فيديوهات أو لم يتم ضبط API Key','error');$('#ytPreview').innerHTML='<div class="ytGrid">'+d.videos.map(v=>`<button type="button" class="ytCard" onclick="pickYouTube('${esc(v.videoId)}','${esc(v.title)}')"><img src="${esc(v.thumbnail)}"><b>${esc(v.title)}</b></button>`).join('')+'</div>'}catch(e){toast(e.message,'error')}}function pickYouTube(id,title){$('#yt').value=id;$('#ytt').value=title;toast('تم اختيار فيديو YouTube ✓')}
function qEditor(q={}){return `<div class="question"><input class="qt" placeholder="السؤال" value="${esc(q.text||'')}" required><input class="qo" placeholder="اختيار 1" value="${esc(q.options?.[0]||'')}" required><input class="qo" placeholder="اختيار 2" value="${esc(q.options?.[1]||'')}" required><input class="qo" placeholder="اختيار 3" value="${esc(q.options?.[2]||'')}" required><input class="qo" placeholder="اختيار 4" value="${esc(q.options?.[3]||'')}" required><select class="qa"><option value="0">الإجابة الصحيحة 1</option><option value="1" ${q.answer===1?'selected':''}>الإجابة الصحيحة 2</option><option value="2" ${q.answer===2?'selected':''}>الإجابة الصحيحة 3</option><option value="3" ${q.answer===3?'selected':''}>الإجابة الصحيحة 4</option></select></div>`}
function openQuiz(q=null){openModal(`<form onsubmit="saveQuiz(event,${q?`'${q.id}'`:'null'})">${gradeSelect()}<select id="lessonId"><option>بدون درس</option></select><label>اسم الاختبار<input id="t" value="${esc(q?.title||'')}" required></label><div class="row"><label>الدقائق<input id="dur" type="number" value="${q?.duration||0}"></label><label>نسبة النجاح<input id="pass" type="number" value="${q?.passingScore??50}"></label></div><div id="qs">${(q?.questions||[{}]).map(qEditor).join('')}</div><button type="button" onclick="$('#qs').insertAdjacentHTML('beforeend',qEditor({}))">＋ سؤال</button><button>حفظ الاختبار</button></form>`);$('#gradeId').onchange=()=>fillLessons($('#gradeId').value);fillLessons(grades[0]?.id||'');if(q)setTimeout(()=>{$('#gradeId').value=q.gradeId;fillLessons(q.gradeId);$('#lessonId').value=q.lessonId||''},20)}function editQuiz(id){openQuiz(quizzes.find(q=>q.id===id))}async function saveQuiz(e,id){e.preventDefault();const questions=$$('#qs .question').map(q=>({text:q.querySelector('.qt').value,options:[...q.querySelectorAll('.qo')].map(x=>x.value),answer:Number(q.querySelector('.qa').value)}));await api(id?'/api/admin/quizzes/'+id:'/api/admin/quizzes',{method:id?'PUT':'POST',body:JSON.stringify({gradeId:$('#gradeId').value,lessonId:$('#lessonId').value||null,title:$('#t').value,duration:Number($('#dur').value)||0,passingScore:Number($('#pass').value)||50,questions})});closeModal();load();tab('quizzes')}
async function deleteGrade(id){if(confirm('حذف الصف بكل محتواه؟'))delEntity('/api/admin/grades/'+id,'الصف')}async function delEntity(u,n){if(!confirm('حذف '+n+'؟'))return;await api(u,{method:'DELETE'});load();toast('تم الحذف ✓')}
function openTeacher(){openModal(`<form onsubmit="saveTeacher(event)"><h2>إضافة مدرس</h2><label>الاسم<input id="n" required></label><label>البريد<input id="e" type="email" required></label><label>كلمة المرور<input id="p" type="password" minlength="8" required></label>${gradeSelect('g',false)}<button>إنشاء</button></form>`)}async function saveTeacher(e){e.preventDefault();await api('/api/admin/teachers',{method:'POST',body:JSON.stringify({name:$('#n').value,email:$('#e').value,password:$('#p').value,gradeId:$('#g').value||null})});closeModal();load();tab('users')}
async function loadSettings(){if(me.role!=='admin')return;const p=await api('/api/admin/site-profile'),s=await api('/api/admin/site-config');$('#profileName').value=p.name||'';$('#profileTitle').value=p.title||'';$('#profileBio').value=p.bio||'';$('#profilePreview').innerHTML=p.image?`<img src="${esc(p.image)}">`:'👤';$('#siteName').value=s.name||'';$('#tagline').value=s.tagline||'';$('#primaryColor').value=s.primaryColor||'#155eef';$('#secondaryColor').value=s.secondaryColor||'#12b886';$('#bgColor').value=s.backgroundColor||'#f6f8fc';$('#heroTitleAdmin').value=s.heroTitle||'';$('#heroTextAdmin').value=s.heroText||'';homeBlocks=Array.isArray(s.homeBlocks)?s.homeBlocks:[];renderHomeBlocksAdmin();$('#phone').value=s.contact?.phone||'';$('#whatsapp').value=s.contact?.whatsapp||'';$('#telegram').value=s.contact?.telegram||'';$('#facebook').value=s.contact?.facebook||'';$('#supportText').value=s.contact?.supportText||'';$('#ytApiStatus').textContent=(await api('/api/site-config')).youtubeApiConfigured?'مضبوط ✓':'غير مضبوط — رابط YouTube اليدوي يعمل بدون API Key'}
$('#profileImage')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>$('#profilePreview').innerHTML=`<img src="${r.result}">`;r.readAsDataURL(f)});

function renderHomeBlocksAdmin(){const b=$('#homeBlocksAdmin');if(!b)return;b.innerHTML=homeBlocks.map((x,i)=>`<div class="card blockEditor"><label>رابط الصورة<input class="hbImg" data-i="${i}" value="${esc(x.image||'')}" placeholder="ارفع صورة أو ضع رابطها"></label><button type="button" onclick="uploadHomeImage(${i})">رفع صورة</button><label>العنوان<input class="hbTitle" data-i="${i}" value="${esc(x.title||'')}"></label><label>النص تحت الصورة<textarea class="hbText" data-i="${i}" rows="3">${esc(x.text||'')}</textarea></label><label>الرابط الاختياري<input class="hbLink" data-i="${i}" value="${esc(x.link||'')}"></label><label>نص الزر<input class="hbButton" data-i="${i}" value="${esc(x.button||'اعرف المزيد')}"></label><button type="button" class="danger" onclick="homeBlocks.splice(${i},1);renderHomeBlocksAdmin()">حذف التصميم</button></div>`).join('')}
function addHomeBlock(){homeBlocks.push({image:'',title:'',text:'',link:'',button:'اعرف المزيد'});renderHomeBlocksAdmin()}
function syncHomeBlocks(){homeBlocks=homeBlocks.map((x,i)=>({...x,image:document.querySelector(`.hbImg[data-i="${i}"]`)?.value||'',title:document.querySelector(`.hbTitle[data-i="${i}"]`)?.value||'',text:document.querySelector(`.hbText[data-i="${i}"]`)?.value||'',link:document.querySelector(`.hbLink[data-i="${i}"]`)?.value||'',button:document.querySelector(`.hbButton[data-i="${i}"]`)?.value||'اعرف المزيد'}))}
async function uploadHomeImage(i){try{const f=await pickFile('image');if(!f)return;const r=await uploadRaw(f);homeBlocks[i].image=r.url;renderHomeBlocksAdmin();toast('تم رفع صورة التصميم ✓')}catch(e){toast(e.message,'error')}}

async function saveSettings(e){e.preventDefault();syncHomeBlocks();let image=$('#profilePreview img')?.src||'';await api('/api/admin/site-profile',{method:'PUT',body:JSON.stringify({name:$('#profileName').value,title:$('#profileTitle').value,bio:$('#profileBio').value,image})});await api('/api/admin/site-config',{method:'PUT',body:JSON.stringify({name:$('#siteName').value,tagline:$('#tagline').value,primaryColor:$('#primaryColor').value,secondaryColor:$('#secondaryColor').value,backgroundColor:$('#bgColor').value,heroTitle:$('#heroTitleAdmin').value,heroText:$('#heroTextAdmin').value,homeBlocks,contact:{phone:$('#phone').value,whatsapp:$('#whatsapp').value,telegram:$('#telegram').value,facebook:$('#facebook').value,supportText:$('#supportText').value}})});toast('تم حفظ شكل وبيانات الموقع ✓')}
async function loadAnalytics(){const a=await api('/api/admin/analytics');$('#analyticsBox').innerHTML=`<div class="stats"><div class="stat">الطلاب<b>${a.students}</b></div><div class="stat">امتحنوا<b>${a.attempted} (${a.attemptedPercent}%)</b></div><div class="stat">لم يمتحنوا<b>${a.notAttempted} (${a.notAttemptedPercent}%)</b></div><div class="stat">ناجحون<b>${a.passed} (${a.passPercent}%)</b></div><div class="stat">راسبون<b>${a.failed} (${a.failPercent}%)</b></div><div class="stat">متوسط الدرجات<b>${a.avgPercent}%</b></div></div><div class="cards">${Object.entries(a.levels).map(([k,v])=>`<article class="card"><h3>${k}</h3><div class="bigNumber">${v}</div></article>`).join('')}</div>`;students=await api('/api/admin/students');$('#studentsTable').innerHTML=students.map(s=>`<div class="resultRow"><b>${esc(s.name)}</b><span>${esc(gradeName(s.gradeId))}</span><span>${s.done} درس</span><span>${s.attempts} اختبار</span><span>${s.lastPercent===null?'لم يمتحن':s.lastPercent+'% '+(s.lastPassed?'ناجح':'راسب')}</span></div>`).join('')}
async function loadParents(){if(me.role!=='admin')return;const u=await api('/api/admin/users');const kids=u.filter(x=>x.role==='student');$('#parentChild').innerHTML=kids.map(x=>`<option value="${x.id}">${esc(x.name)} — ${esc(gradeName(x.gradeId))}</option>`).join('')||'<option value="">لا يوجد طلاب</option>'}
async function saveParent(e){e.preventDefault();await api('/api/admin/parents',{method:'POST',body:JSON.stringify({name:$('#pn').value,email:$('#pe').value,password:$('#pp').value,phone:$('#pPhone').value,childId:$('#parentChild').value})});toast('تم إنشاء حساب ولي الأمر ✓');e.target.reset()}
async function loadMedia(){try{const m=await api('/api/admin/media');$('#mediaList').innerHTML=m.slice().reverse().map(x=>`<div class="resultRow"><span>${x.type==='video'?'🎞️':x.type==='pdf'?'📄':'🖼️'}</span><b>${esc(x.name)}</b><a href="${esc(x.url)}" target="_blank">فتح</a></div>`).join('')||empty('لا توجد ملفات')}catch(e){toast(e.message,'error')}}
async function boot(){try{me=await api('/api/me');if(!['admin','teacher'].includes(me.role))throw Error('لا توجد صلاحية إدارة');$('#adminWelcome').textContent=`مرحبًا ${esc(me.name)} — ${me.role==='admin'?'مدير المنصة':'مدرس'}`;if(me.role!=='admin'){['users','settings','parents'].forEach(x=>document.querySelector(`[data-tab="${x}"]`)?.classList.add('hidden'))}await load();tab('dashboard')}catch(e){document.body.innerHTML=`<main><div class="card"><h2>لا توجد صلاحية للدخول</h2><p>${esc(e.message)}</p><button onclick="parent.openLogin()">تسجيل الدخول</button></div></main>`}}boot();
