function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}let token=localStorage.getItem('mostakshef_token'),me,grades=[],lessons=[],quizzes=[],site={};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function escapeHtml(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function H(){return {'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})}}
async function api(u,o={}){const r=await fetch(u,{...o,headers:{...H(),...(o.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'حدث خطأ');return d}
function go(v){$$('.view').forEach(x=>x.classList.toggle('hidden',x.id!==v));if(v==='grades')renderGrades();if(v==='lessons')renderLessons();if(v==='quizzes')renderQuizzes();if(v==='dashboard')renderDash();window.scrollTo(0,0)}
$$('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));
function openModal(x){$('#modalBody').innerHTML=x;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function openLogin(){openModal(`<h2>تسجيل الدخول</h2><form id="lf"><input id="le" type="email" placeholder="البريد الإلكتروني" required><input id="lp" type="password" placeholder="كلمة المرور" required><button>دخول</button></form><p class="muted">ولي الأمر؟ <a href="/parent.html">ادخل من صفحة ولي الأمر</a></p>`);$('#lf').onsubmit=login}
function openRegister(){openModal(`<h2>إنشاء حساب طالب</h2><form id="rf"><input id="rn" placeholder="الاسم" required><input id="re" type="email" placeholder="البريد الإلكتروني" required><input id="rp" type="password" minlength="8" placeholder="كلمة المرور (8 أحرف على الأقل)" required><select id="rg">${grades.map(g=>`<option value="${escapeHtml(g.id)}">${escapeHtml(g.name)}</option>`).join('')}</select><button>إنشاء الحساب</button></form>`);$('#rf').onsubmit=register}
async function login(e){e.preventDefault();try{const d=await api('/api/login',{method:'POST',body:JSON.stringify({email:$('#le').value,password:$('#lp').value})});token=d.token;localStorage.setItem('mostakshef_token',token);await boot();closeModal()}catch(x){alert(x.message)}}
async function register(e){e.preventDefault();try{const d=await api('/api/register',{method:'POST',body:JSON.stringify({name:$('#rn').value,email:$('#re').value,password:$('#rp').value,gradeId:$('#rg').value})});token=d.token;localStorage.setItem('mostakshef_token',token);await boot();closeModal()}catch(x){alert(x.message)}}
function authArea(){if(!me){$('#authArea').innerHTML='<button onclick="openLogin()">دخول</button><button class="secondary" onclick="openRegister()">إنشاء حساب</button>';$('#adminNav').classList.add('hidden');return}if(me.role==='parent'){location.href='/parent.html';return}$('#authArea').innerHTML=`<span>مرحبًا، ${escapeHtml(me.name)}</span><button onclick="logout()">خروج</button>`;$('#adminNav').classList.toggle('hidden',!['admin','teacher'].includes(me.role))}
function logout(){localStorage.removeItem('mostakshef_token');token=null;me=null;authArea();go('home')}
function gradeOptions(){return '<option value="">كل الصفوف</option>'+grades.map(g=>`<option value="${escapeHtml(g.id)}">${escapeHtml(g.name)}</option>`).join('')}
function renderGrades(){$('#allGrades').innerHTML=grades.map(g=>`<article class="card"><div class="icon">🎓</div><h3>${escapeHtml(g.name)}</h3><p>${g.stage==='primary'?'المرحلة الابتدائية':'المرحلة الإعدادية'}</p><button onclick="filterLessons('${g.id}')">استكشف الدروس</button></article>`).join('')}
function filterLessons(g){go('lessons');$('#lessonGrade').value=g;renderLessons()}
function renderLessons(){const g=$('#lessonGrade').value,term=(($('#lessonSearch')?.value)||'').trim().toLowerCase(),a=lessons.filter(l=>(!g||l.gradeId===g)&&(!term||`${l.title} ${l.summary||''}`.toLowerCase().includes(term)));$('#lessonCards').innerHTML=a.length?a.map(l=>`<article class="card"><span class="tag">${escapeHtml(gradeName(l.gradeId))}</span><h3>${escapeHtml(l.title)}</h3><p>${escapeHtml(l.summary||'')}</p><div class="metaLine">${l.youtubeId||l.videoUrl?'🎬 فيديو':'📖 درس'} · ${l.resources?.length||0} ملف</div><button onclick="openLesson('${l.id}')">فتح الدرس</button></article>`).join(''):'<div class="notice">لا توجد دروس لهذا الصف حاليًا.</div>'}
function renderQuizzes(){const g=$('#quizGrade').value,a=quizzes.filter(q=>!g||q.gradeId===g);$('#quizCards').innerHTML=a.length?a.map(q=>`<article class="card"><span class="tag">${escapeHtml(gradeName(q.gradeId))}</span><h3>${escapeHtml(q.title)}</h3><p>${q.questions.length} سؤال · نجاح من ${q.passingScore||50}%</p><button onclick="startQuiz('${q.id}')">ابدأ الاختبار</button></article>`).join(''):'<div class="notice">لا توجد اختبارات لهذا الصف حاليًا.</div>'}
function gradeName(id){return grades.find(g=>g.id===id)?.name||'—'}
function lessonResources(l){return (l.resources||[]).map(r=>r.type==='pdf'?`<a class="resource" href="${escapeHtml(r.url)}" target="_blank">📄 ${escapeHtml(r.name||'ملف PDF')}</a>`:r.type==='image'?`<img class="lessonImg" src="${escapeHtml(r.url)}" alt="${escapeHtml(r.name||'صورة الدرس')}">`:`<a class="resource" href="${escapeHtml(r.url)}" target="_blank">🎬 ${escapeHtml(r.name||'فيديو')}</a>`).join('')}
async function openLesson(id){const l=lessons.find(x=>x.id===id);if(!l)return;let video='';if(l.youtubeId)video=`<div class="videoWrap"><iframe id="ytPlayer" src="https://www.youtube.com/embed/${encodeURIComponent(l.youtubeId)}?enablejsapi=1" title="${escapeHtml(l.youtubeTitle||l.title)}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>`;else if(l.videoUrl)video=`<div class="videoWrap"><video id="localVideo" controls playsinline src="${escapeHtml(l.videoUrl)}"></video></div><a class="resource" href="${escapeHtml(l.videoUrl)}" download>⬇️ تحميل فيديو الدرس</a>`;const pct=me?.lessonWatch?.[id]||0;openModal(`<span class="tag">${escapeHtml(gradeName(l.gradeId))}</span><h2>${escapeHtml(l.title)}</h2>${l.coverImage?`<img class="lessonCover" src="${escapeHtml(l.coverImage)}">`:''}<p>${escapeHtml(l.summary||'')}</p>${video}<div class="lessonContent">${escapeHtml(l.content||'لا يوجد محتوى بعد.').replace(/\n/g,'<br>')}</div><div class="resources">${lessonResources(l)}</div>${me?`<div class="watchBox"><div>تقدم مشاهدة الدرس: <b id="watchPct">${pct}%</b></div><div class="progress"><i id="watchBar" style="width:${pct}%"></i></div><button onclick="complete('${id}',100)">✓ تم إنهاء الدرس</button></div>`:'<div class="notice">سجّل الدخول لحفظ تقدمك.</div>'}`);if(l.videoUrl&&me){const v=$('#localVideo');v?.addEventListener('timeupdate',()=>{if(v.duration){const p=Math.round(v.currentTime/v.duration*100);if(p%10===0)saveWatch(id,p)}})}}
let lastWatch={};async function saveWatch(id,p){if(!me||Date.now()-(lastWatch[id]||0)<4000)return;lastWatch[id]=Date.now();try{await api('/api/progress',{method:'POST',body:JSON.stringify({lessonId:id,completed:p>=90,percent:p})});me=await api('/api/me');if($('#watchPct'))$('#watchPct').textContent=p+'%';if($('#watchBar'))$('#watchBar').style.width=p+'%'}catch(e){}}
async function complete(id,p=100){try{await api('/api/progress',{method:'POST',body:JSON.stringify({lessonId:id,completed:true,percent:p})});me=await api('/api/me');if($('#watchPct'))$('#watchPct').textContent='100%';if($('#watchBar'))$('#watchBar').style.width='100%';alert('تم حفظ تقدمك ✓');renderDash()}catch(x){alert(x.message)}}
async function startQuiz(id){if(!me){openLogin();return}const q=await api('/api/quizzes/'+id),startedAt=new Date().toISOString();let timer=null;openModal(`<h2>${escapeHtml(q.title)}</h2>${q.duration?`<div class="timer" id="timer">الوقت: ${q.duration}:00</div>`:''}<form id="qf">${q.questions.map((x,i)=>`<div class="question"><b>${i+1}. ${escapeHtml(x.text)}</b>${x.options.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}" required> ${escapeHtml(o)}</label>`).join('')}</div>`).join('')}<button>إرسال الإجابات</button></form>`);if(q.duration){const end=Date.now()+q.duration*60000;timer=setInterval(()=>{const sec=Math.max(0,Math.ceil((end-Date.now())/1000));$('#timer').textContent='الوقت: '+Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');if(sec===0){clearInterval(timer);$('#qf').requestSubmit()}},250)}$('#qf').onsubmit=async e=>{e.preventDefault();const a=q.questions.map((_,i)=>Number(document.querySelector('input[name="q'+i+'"]:checked').value));try{if(timer)clearInterval(timer);const r=await api('/api/quizzes/'+id+'/submit',{method:'POST',body:JSON.stringify({answers:a,startedAt})});openModal(`<h2>${r.passed?'أحسنت! 🎉':'راجع الدرس وحاول مرة أخرى'}</h2><div class="result">${r.score} / ${r.total}</div><p>نسبتك: ${r.percent}% — ${r.passed?'ناجح':'راسب'}</p><button onclick="closeModal();go('dashboard')">عرض تقدمي</button>`);me=await api('/api/me')}catch(x){alert(x.message)}}}
function renderDash(){if(!me){$('#studentDash').innerHTML='<div class="card"><h2>سجّل الدخول أولًا</h2><button onclick="openLogin()">تسجيل الدخول</button></div>';return}const own=lessons.filter(l=>l.gradeId===me.gradeId),done=own.filter(l=>me.progress?.[l.id]).length,att=me.attempts||[],pct=own.length?Math.round(done/own.length*100):0;$('#studentDash').innerHTML=`<div class="stats"><div class="stat">نسبة الإنجاز<b>${pct}%</b></div><div class="stat">الدروس المكتملة<b>${done}/${own.length}</b></div><div class="stat">الاختبارات<b>${att.length}</b></div></div><div class="card"><h2>${escapeHtml(me.name)}</h2><p>${escapeHtml(me.email)}</p><div class="progress"><i style="width:${pct}%"></i></div><h3>آخر النتائج</h3>${att.length?att.slice(-5).reverse().map(a=>`<p>النتيجة: <b>${a.score}/${a.total}</b> — ${a.percent}% — ${a.passed?'ناجح':'راسب'}</p>`).join(''):'<p class="muted">لم تؤدِّ اختبارات بعد.</p>'}</div>`}
function applyTheme(){document.documentElement.style.setProperty('--primary',site.site?.primaryColor||'#155eef');document.documentElement.style.setProperty('--secondary',site.site?.secondaryColor||'#12b886');document.documentElement.style.setProperty('--bg',site.site?.backgroundColor||'#f6f8fc');document.title=(site.site?.name||'مستكشف')+' | منصة الدراسات الاجتماعية';$('.brand').innerHTML='🧭 '+escapeHtml(site.site?.name||'مستكشف');const h=$('#heroTitle'),t=$('#heroText');if(h)h.innerHTML=escapeHtml(site.site?.heroTitle||'اتعلّم الدراسات الاجتماعية بطريقة أسهل وأمتع').replace(/\n/g,'<br>');if(t)t.textContent=site.site?.heroText||'';$('#siteTagline').textContent=site.site?.tagline||'';const c=site.contact||{};$('#contactLinks').innerHTML=[['whatsapp','واتساب','https://wa.me/'],['telegram','تليجرام','https://t.me/'],['facebook','فيسبوك','']].filter(x=>c[x[0]]).map(x=>`<a class="contactBtn" href="${escapeHtml(x[0]==='whatsapp'?('https://wa.me/'+String(c.whatsapp).replace(/\D/g,'')):c[x[0]])}" target="_blank">${x[1]}</a>`).join('')}
function renderHomeBlocks(){const blocks=site.homeBlocks||[];$('#homeBlocks').innerHTML=blocks.map(b=>`<article class="homeBlock"><img src="${escapeHtml(b.image||'')}" alt="${escapeHtml(b.title||'')}"><div><h3>${escapeHtml(b.title||'')}</h3><p>${escapeHtml(b.text||'')}</p>${b.link?`<a href="${escapeHtml(b.link)}" target="_blank">${escapeHtml(b.button||'اعرف المزيد')} ↗</a>`:''}</div></article>`).join('')}
async function boot(){try{site=await api('/api/site-config');applyTheme();renderHomeBlocks();$('#ytChannel').href=site.youtubeChannel||'#';if(site.profile){$('#profileNameHome').textContent=site.profile.name||'محمد الفقي';$('#profileTitleHome').textContent=site.profile.title||'';$('#profileBioHome').textContent=site.profile.bio||'';if(site.profile.image)$('#profileImageHome').innerHTML=`<img src="${escapeHtml(site.profile.image)}" alt="${escapeHtml(site.profile.name||'محمد الفقي')}">`}grades=await api('/api/grades');lessons=await api('/api/lessons');quizzes=await api('/api/quizzes');if(token)me=await api('/api/me')}catch(e){console.error(e)}$('#homeGrades').innerHTML=grades.map(g=>`<article class="card"><div class="icon">🗺️</div><h3>${escapeHtml(g.name)}</h3><button onclick="filterLessons('${g.id}')">ابدأ</button></article>`).join('');$('#lessonGrade').innerHTML=gradeOptions();$('#quizGrade').innerHTML=gradeOptions();$('#lessonGrade').onchange=renderLessons;$('#quizGrade').onchange=renderQuizzes;authArea();renderGrades();renderLessons();renderQuizzes();renderDash()}
boot();
